#Netplan NetworkManager
network:
  version: 2
  renderer: NetworkManager
  ethernets:
     ens160:
       dhcp4: no
       addresses: [192.168.112.158/24]
       gateway4: [192.168.112.1]
       nameservers:
         addresses: [8.8.8.8]